### PR TITLE
Add fish shell completion

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by rhaberkorn** [comment]
I don't use "fish". But the patch looks good. Could you add a default value for `FISH_COMPLETIONSDIR`? If possible, query it via pkg-config or by some other means.

**Comment by rhaberkorn** [comment]
Also add a few lines to README - how to add aliases.

**Comment by ghost** [comment]
Done. I added a default for `FISH_COMPLETIONSDIR` and the alias commands to the README.

I'm not familiar with shell completion because I usually avoid it, but I do use fish and completion for this command is especially useful.

**Comment by rhaberkorn** [comment]
I still had to fix this up. Tested it - works fine.

**Pull request merged**
